# Generated by Django 3.2.23 on 2023-11-30 08:51

from django.db import migrations
import froala_editor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_alter_comment_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='content',
            field=froala_editor.fields.FroalaField(blank=True),
        ),
    ]
