# Generated by Django 3.2.23 on 2023-12-02 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_post_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='content',
        ),
    ]
