# Generated by Django 4.2.6 on 2023-11-05 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_alter_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='gender',
            field=models.CharField(choices=[('male', 0), ('female', 1)], default=1, max_length=10),
            preserve_default=False,
        ),
    ]
