# Generated by Django 4.2.6 on 2023-11-05 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_profile_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.CharField(choices=[(0, 'Male'), (1, 'FeMale')], max_length=10),
        ),
    ]
