# Generated by Django 4.2.6 on 2023-11-05 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_alter_profile_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='image',
        ),
    ]
