# Generated by Django 3.2.23 on 2023-12-03 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0011_profile_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='photo',
        ),
    ]
