# Generated by Django 4.2.7 on 2024-11-20 07:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_postsaved'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PostSaved',
        ),
    ]
